version: '3.9'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:16
    ports:
      - "5433:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=article





volumes:
  postgresql_data:
    driver: local